apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practica
  template:
    metadata:
      labels:
        app: practica
    spec:
      containers:
        - name: practica
          image: 0322103693/practica:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: practica-service
spec:
  selector:
    app: practica
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

